collections:
  authors:
    output: true
  react:
    output: true
  blog:
    output: true
  javascript:
    output: true
  webpack:
    output: true

defaults:
  - scope:
      path: ''
      type: 'authors'
    values:
      layout: 'author'
      image: '/assets/images/default-image.jpg'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      image: '/assets/images/default-image.jpg'
  - scope:
      path: ''
      type: 'react'
    values:
      layout: 'post'
      image: '/assets/images/default-image.jpg'
  - scope:
      path: ''
    values:
      layout: 'default'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
